# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ThirdPartyPractice' do
pod 'DSLCalendarView', '~> 0.0.1'
pod 'iOS-Slide-Menu', '~> 1.4.0'
pod 'JTCalendar', '~> 1.1'
end

target 'ThirdPartyPracticeTests' do

end

