# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CocoapodsUiSwift' do
pod 'MBCalendarKit', '~>3.0.4'
end

target 'CocoapodsUiSwiftTests' do
pod 'MBCalendarKit', '~>3.0.4'
end

